### PR TITLE
Show the correct exception message for cURL errors

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
I've noticed that every time a cURL error is thrown the exception message only says "Unknown error" instead of something helpful:
```
2017-03-31T08:19:34+02:00 CRIT (2): airmoi\FileMaker\FileMakerException: Unknown error in /xx/vendor/airmoi/filemaker/src/FileMaker.php:802
Stack trace:
#0 /xxx/vendor/airmoi/filemaker/src/Command/Find.php(109): airmoi\FileMaker\FileMaker->execute(Array)
#1 /xx/yy/AbstractFmRepository.php(272): airmoi\FileMaker\Command\Find->execute()
```

Although if I go to FileMaker.php at line 802 I see something helpful! The problem is that the exception receiving the curl error number as error code and rewrites the message based on the FM messages.

This is just a quick fix by omitting the curl error number in such cases.

A more complete fix would be to introduce a second Exception (thats inheriting from FileMakerException) would do this kind of rewriting. What do you think?

### CODE REVIEW

**Comment by airmoi** [comment]
Hi Matthias,

Thank for the fix. I completely agree with the idea of having another exception Class for such errors.
That's something that always annoy me with the old API, where curl issues where hard to diagnose.

I'll work on that for the next release

**Comment by MatthiasKuehneEllerhold** [comment]
Im a little bit at loss on the current state of this PR. I tried rebasing it on develop but got a huge load of conflict.s
It seems like you merged it into develop and added a new method for it `handleCurlError` ? Should I close this PR?

**Comment by airmoi** [comment]
Yep, I just figured out that it was something I had already solved in develop.
I just have to release 2.2 (after some testing)

**Comment by MatthiasKuehneEllerhold** [comment]
hey Romain (ping @airmoi). Could you tell me pls when you want to release the 2.2.0? I've got a lot of unknown errors as of lately and its a PITA to debug them ... because they're always "unknown" instead of something helpful!
Thanks!

**Comment by airmoi** [comment]
Hi Mattthias,

Sorry, I've been quite busy theses last months, I will release the fix by the end of the week

**Comment by MatthiasKuehneEllerhold** [comment]
Thank you very much!

**Comment by airmoi** [comment]
Here it is, the [2.2.0](https://github.com/airmoi/FileMaker/releases/tag/2.2.0) version is live

**Comment by mrchimp** [comment]
Much appreciated!

**Pull request closed without merging**
